Display identity creation error details
Concordium/concordium-desktop-wallet pull request #167
Opened 2021-11-18 11:39 UTC by orhoj

## Purpose
Notabene now provides error message details in the `detail` field. This PR ensures that we save that information on rejected identities, and that we display the message to the user.

## Changes
- `detail` is saved in the identity table if the identity creation fails.
- the `detail` field is displayed for failed identities.

## Checklist
- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2021-11-19 10:56 UTC, soerenbf requested changes
As agreed, I pushed some changes to the presentation on the `IdentityCard`.

If an account is rejected, I get an error about checking the node status, as the account address isn't on chain. Should be able to avoid this?

![Screenshot 2021-11-19 at 11 49 48](https://user-images.githubusercontent.com/828403/142611214-2508c9de-a78a-47c4-895a-5ef1f6b70272.png)

2021-11-19 13:56 UTC, soerenbf commented
Could also link this PR to #165

2021-11-22 08:29 UTC, orhoj commented on app/components/FailedIdentityModal.tsx
> +    const decriptionComponent = useMemo(() => {
I renamed it to `description`.

2021-11-22 08:30 UTC, orhoj commented
> As agreed, I pushed some changes to the presentation on the `IdentityCard`.
> 
> If an account is rejected, I get an error about checking the node status, as the account address isn't on chain. Should be able to avoid this?
> 
> ![Screenshot 2021-11-19 at 11 49 48](https://user-images.githubusercontent.com/828403/142611214-2508c9de-a78a-47c4-895a-5ef1f6b70272.png)

Yeah. That should not be happening, but it may be related to the node-sdk changes Søren made. It is, however, unrelated to this PR.

2021-11-22 08:42 UTC, soerenbf commented
> > As agreed, I pushed some changes to the presentation on the `IdentityCard`.
> > If an account is rejected, I get an error about checking the node status, as the account address isn't on chain. Should be able to avoid this?

> Yeah. That should not be happening, but it may be related to the node-sdk changes Søren made. It is, however, unrelated to this PR.

I'll file a bug instead.

2021-11-22 08:42 UTC, soerenbf approved these changes

2021-11-22 09:15 UTC, merged