Add CCD as option to account report
Concordium/concordium-desktop-wallet pull request #228
Opened 2022-03-02 08:57 UTC by shjortConcordium

## Purpose

Implement #222 

## Changes

Added radio buttons to decide unit in account report.
 + convert the unit to CCD if that unit is chosen.
Add unit to headers in the reports.
Also changed gtu.ts to ccd.ts and renamed function/variables in it to say CCD instead of gtu.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2022-03-02 12:33 UTC, soerenbf requested changes
When I generate a report, there is a popup showing quickly with the text "Generating report". Not that I mind that I get some feedback on the action, but it disappears too quickly to add any value. Maybe if you make the button enter a "loading" state + disable clicking the button again while the action is being performed?

Other than that, I think it looks good.

2022-03-04 14:22 UTC, shjortConcordium commented
> When I generate a report, there is a popup showing quickly with the text "Generating report". Not that I mind that I get some feedback on the action, but it disappears too quickly to add any value. Maybe if you make the button enter a "loading" state + disable clicking the button again while the action is being performed?
> Screen.Recording.2022-03-02.at.13.29.09.mov
> 
> Other than that, I think it looks good.

Hmm, it is mainly helpful for accounts that have many transactions (i.e. finalizers), and this way they can't click away from the page while the report is being created.

2022-03-07 07:01 UTC, soerenbf commented
> > When I generate a report, there is a popup showing quickly with the text "Generating report". Not that I mind that I get some feedback on the action, but it disappears too quickly to add any value. Maybe if you make the button enter a "loading" state + disable clicking the button again while the action is being performed?
> > Screen.Recording.2022-03-02.at.13.29.09.mov
> > Other than that, I think it looks good.
> 
> Hmm, it is mainly helpful for accounts that have many transactions (i.e. finalizers), and this way they can't click away from the page while the report is being created.

I guess that's fine then.. Don't think many people will be using this feature for accounts with a small amount of transactions anyway?

2022-03-08 07:47 UTC, soerenbf commented on app/pages/Accounts/AccountDetailsPage/UpdateBakerStake.tsx
> +import { displayAsCCD, microCCDToCCD, toMicroUnits } from '~/utils/ccd';
`microCcdToCcd` and `ccdToMicroCcd`? Do we generally all-uppercase CCD in the codebase?

2022-03-08 08:44 UTC, shjortConcordium commented on app/pages/Accounts/AccountDetailsPage/UpdateBakerStake.tsx
> +import { displayAsCCD, microCCDToCCD, toMicroUnits } from '~/utils/ccd';
No, except the vars/functions in ccd.ts.
I've changed it to  `microCcdToCcd` and changed the others to use **ccd** instead of **CCD**.

2022-03-09 07:14 UTC, soerenbf approved these changes

2022-03-09 08:27 UTC, merged