Update timeout parameters
Concordium/concordium-desktop-wallet pull request #346
Opened 2023-09-18 09:01 UTC by shjortConcordium

## Purpose

Support the `timeout parameters` update.

## Changes

- Added "no" unit default for `RelativeRateField`.
- Added the flow for the update.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2023-09-19 13:11 UTC, orhoj requested changes

2023-09-19 14:07 UTC, shjortConcordium commented on app/pages/multisig/updates/TimeoutParameters/UpdateTimeoutParameters.tsx
> +    parseInt(value.numerator, 10) > parseInt(value.denominator, 10) ||
Well it can lead to some false positives/negatives, so I'll fix it.

2023-09-20 06:49 UTC, orhoj commented on app/pages/multisig/updates/TimeoutParameters/UpdateTimeoutParameters.tsx
> +    BigInt(value.numerator) > BigInt(value.denominator) || 'Value must above 1';
```suggestion
    BigInt(value.numerator) > BigInt(value.denominator) || 'Value must be above 1';
```

2023-09-20 06:50 UTC, orhoj approved these changes

2023-09-20 08:20 UTC, merged